services:
    takeoffset.api.client:
        class: Takeoffset\ApiBundle\Services\Client
        arguments: [%takeoffset_api%, @?logger]
        tags:
            - { name: monolog.logger, channel: client }

    takeoffset.api.offset:
        class: Takeoffset\ApiBundle\Services\OffsetService
        arguments: [@takeoffset.api.client]
    takeoffset.api.trade:
        class: Takeoffset\ApiBundle\Services\TradeService
        arguments: [@takeoffset.api.client]
    takeoffset.api.distance:
        class: Takeoffset\ApiBundle\Services\DistanceService
        arguments: [@takeoffset.api.client]
    takeoffset.api.invoice:
        class: Takeoffset\ApiBundle\Services\InvoiceService
        arguments: [@takeoffset.api.client]
    takeoffset.api.receipt:
        class: Takeoffset\ApiBundle\Services\ReceiptService
        arguments: [@takeoffset.api.client]
    takeoffset.api.user:
        class: Takeoffset\ApiBundle\Services\UserService
        arguments: [@takeoffset.api.client]
    takeoffset.api.airport:
        class: Takeoffset\ApiBundle\Services\AirportService
        arguments: [@takeoffset.api.client]
